export interface Country {
  code: string
  dial: string
  en: string
  ru: string
}

/** All 193 UN member states plus Vatican City, Palestine, Kosovo, Taiwan, Hong Kong and Macau (199 total). */
export const COUNTRIES: Country[] = [
  { code: 'DZ', dial: '213', en: "Algeria", ru: "Алжир" },
  { code: 'AO', dial: '244', en: "Angola", ru: "Ангола" },
  { code: 'BJ', dial: '229', en: "Benin", ru: "Бенин" },
  { code: 'BW', dial: '267', en: "Botswana", ru: "Ботсвана" },
  { code: 'BF', dial: '226', en: "Burkina Faso", ru: "Буркина-Фасо" },
  { code: 'BI', dial: '257', en: "Burundi", ru: "Бурунди" },
  { code: 'CV', dial: '238', en: "Cabo Verde", ru: "Кабо-Верде" },
  { code: 'CM', dial: '237', en: "Cameroon", ru: "Камерун" },
  { code: 'CF', dial: '236', en: "Central African Republic", ru: "Центральноафриканская Республика" },
  { code: 'TD', dial: '235', en: "Chad", ru: "Чад" },
  { code: 'KM', dial: '269', en: "Comoros", ru: "Коморы" },
  { code: 'CG', dial: '242', en: "Congo (Republic)", ru: "Республика Конго" },
  { code: 'CD', dial: '243', en: "DR Congo", ru: "Демократическая Республика Конго" },
  { code: 'CI', dial: '225', en: "Côte d'Ivoire", ru: "Кот-д'Ивуар" },
  { code: 'DJ', dial: '253', en: "Djibouti", ru: "Джибути" },
  { code: 'EG', dial: '20', en: "Egypt", ru: "Египет" },
  { code: 'GQ', dial: '240', en: "Equatorial Guinea", ru: "Экваториальная Гвинея" },
  { code: 'ER', dial: '291', en: "Eritrea", ru: "Эритрея" },
  { code: 'SZ', dial: '268', en: "Eswatini", ru: "Эсватини" },
  { code: 'ET', dial: '251', en: "Ethiopia", ru: "Эфиопия" },
  { code: 'GA', dial: '241', en: "Gabon", ru: "Габон" },
  { code: 'GM', dial: '220', en: "Gambia", ru: "Гамбия" },
  { code: 'GH', dial: '233', en: "Ghana", ru: "Гана" },
  { code: 'GN', dial: '224', en: "Guinea", ru: "Гвинея" },
  { code: 'GW', dial: '245', en: "Guinea-Bissau", ru: "Гвинея-Бисау" },
  { code: 'KE', dial: '254', en: "Kenya", ru: "Кения" },
  { code: 'LS', dial: '266', en: "Lesotho", ru: "Лесото" },
  { code: 'LR', dial: '231', en: "Liberia", ru: "Либерия" },
  { code: 'LY', dial: '218', en: "Libya", ru: "Ливия" },
  { code: 'MG', dial: '261', en: "Madagascar", ru: "Мадагаскар" },
  { code: 'MW', dial: '265', en: "Malawi", ru: "Малави" },
  { code: 'ML', dial: '223', en: "Mali", ru: "Мали" },
  { code: 'MR', dial: '222', en: "Mauritania", ru: "Мавритания" },
  { code: 'MU', dial: '230', en: "Mauritius", ru: "Маврикий" },
  { code: 'MA', dial: '212', en: "Morocco", ru: "Марокко" },
  { code: 'MZ', dial: '258', en: "Mozambique", ru: "Мозамбик" },
  { code: 'NA', dial: '264', en: "Namibia", ru: "Намибия" },
  { code: 'NE', dial: '227', en: "Niger", ru: "Нигер" },
  { code: 'NG', dial: '234', en: "Nigeria", ru: "Нигерия" },
  { code: 'RW', dial: '250', en: "Rwanda", ru: "Руанда" },
  { code: 'ST', dial: '239', en: "Sao Tome and Principe", ru: "Сан-Томе и Принсипи" },
  { code: 'SN', dial: '221', en: "Senegal", ru: "Сенегал" },
  { code: 'SC', dial: '248', en: "Seychelles", ru: "Сейшелы" },
  { code: 'SL', dial: '232', en: "Sierra Leone", ru: "Сьерра-Леоне" },
  { code: 'SO', dial: '252', en: "Somalia", ru: "Сомали" },
  { code: 'ZA', dial: '27', en: "South Africa", ru: "ЮАР" },
  { code: 'SS', dial: '211', en: "South Sudan", ru: "Южный Судан" },
  { code: 'SD', dial: '249', en: "Sudan", ru: "Судан" },
  { code: 'TZ', dial: '255', en: "Tanzania", ru: "Танзания" },
  { code: 'TG', dial: '228', en: "Togo", ru: "Того" },
  { code: 'TN', dial: '216', en: "Tunisia", ru: "Тунис" },
  { code: 'UG', dial: '256', en: "Uganda", ru: "Уганда" },
  { code: 'ZM', dial: '260', en: "Zambia", ru: "Замбия" },
  { code: 'ZW', dial: '263', en: "Zimbabwe", ru: "Зимбабве" },
  { code: 'CA', dial: '1', en: "Canada", ru: "Канада" },
  { code: 'US', dial: '1', en: "United States", ru: "США" },
  { code: 'MX', dial: '52', en: "Mexico", ru: "Мексика" },
  { code: 'BZ', dial: '501', en: "Belize", ru: "Белиз" },
  { code: 'CR', dial: '506', en: "Costa Rica", ru: "Коста-Рика" },
  { code: 'SV', dial: '503', en: "El Salvador", ru: "Сальвадор" },
  { code: 'GT', dial: '502', en: "Guatemala", ru: "Гватемала" },
  { code: 'HN', dial: '504', en: "Honduras", ru: "Гондурас" },
  { code: 'NI', dial: '505', en: "Nicaragua", ru: "Никарагуа" },
  { code: 'PA', dial: '507', en: "Panama", ru: "Панама" },
  { code: 'AG', dial: '1', en: "Antigua and Barbuda", ru: "Антигуа и Барбуда" },
  { code: 'BS', dial: '1', en: "Bahamas", ru: "Багамы" },
  { code: 'BB', dial: '1', en: "Barbados", ru: "Барбадос" },
  { code: 'CU', dial: '53', en: "Cuba", ru: "Куба" },
  { code: 'DM', dial: '1', en: "Dominica", ru: "Доминика" },
  { code: 'DO', dial: '1', en: "Dominican Republic", ru: "Доминиканская Республика" },
  { code: 'GD', dial: '1', en: "Grenada", ru: "Гренада" },
  { code: 'HT', dial: '509', en: "Haiti", ru: "Гаити" },
  { code: 'JM', dial: '1', en: "Jamaica", ru: "Ямайка" },
  { code: 'KN', dial: '1', en: "Saint Kitts and Nevis", ru: "Сент-Китс и Невис" },
  { code: 'LC', dial: '1', en: "Saint Lucia", ru: "Сент-Люсия" },
  { code: 'VC', dial: '1', en: "Saint Vincent and the Grenadines", ru: "Сент-Винсент и Гренадины" },
  { code: 'TT', dial: '1', en: "Trinidad and Tobago", ru: "Тринидад и Тобаго" },
  { code: 'AR', dial: '54', en: "Argentina", ru: "Аргентина" },
  { code: 'BO', dial: '591', en: "Bolivia", ru: "Боливия" },
  { code: 'BR', dial: '55', en: "Brazil", ru: "Бразилия" },
  { code: 'CL', dial: '56', en: "Chile", ru: "Чили" },
  { code: 'CO', dial: '57', en: "Colombia", ru: "Колумбия" },
  { code: 'EC', dial: '593', en: "Ecuador", ru: "Эквадор" },
  { code: 'GY', dial: '592', en: "Guyana", ru: "Гайана" },
  { code: 'PY', dial: '595', en: "Paraguay", ru: "Парагвай" },
  { code: 'PE', dial: '51', en: "Peru", ru: "Перу" },
  { code: 'SR', dial: '597', en: "Suriname", ru: "Суринам" },
  { code: 'UY', dial: '598', en: "Uruguay", ru: "Уругвай" },
  { code: 'VE', dial: '58', en: "Venezuela", ru: "Венесуэла" },
  { code: 'AF', dial: '93', en: "Afghanistan", ru: "Афганистан" },
  { code: 'AM', dial: '374', en: "Armenia", ru: "Армения" },
  { code: 'AZ', dial: '994', en: "Azerbaijan", ru: "Азербайджан" },
  { code: 'BH', dial: '973', en: "Bahrain", ru: "Бахрейн" },
  { code: 'BD', dial: '880', en: "Bangladesh", ru: "Бангладеш" },
  { code: 'BT', dial: '975', en: "Bhutan", ru: "Бутан" },
  { code: 'BN', dial: '673', en: "Brunei", ru: "Бруней" },
  { code: 'KH', dial: '855', en: "Cambodia", ru: "Камбоджа" },
  { code: 'CN', dial: '86', en: "China", ru: "Китай" },
  { code: 'CY', dial: '357', en: "Cyprus", ru: "Кипр" },
  { code: 'GE', dial: '995', en: "Georgia", ru: "Грузия" },
  { code: 'IN', dial: '91', en: "India", ru: "Индия" },
  { code: 'ID', dial: '62', en: "Indonesia", ru: "Индонезия" },
  { code: 'IR', dial: '98', en: "Iran", ru: "Иран" },
  { code: 'IQ', dial: '964', en: "Iraq", ru: "Ирак" },
  { code: 'IL', dial: '972', en: "Israel", ru: "Израиль" },
  { code: 'JP', dial: '81', en: "Japan", ru: "Япония" },
  { code: 'JO', dial: '962', en: "Jordan", ru: "Иордания" },
  { code: 'KZ', dial: '7', en: "Kazakhstan", ru: "Казахстан" },
  { code: 'KW', dial: '965', en: "Kuwait", ru: "Кувейт" },
  { code: 'KG', dial: '996', en: "Kyrgyzstan", ru: "Киргизия" },
  { code: 'LA', dial: '856', en: "Laos", ru: "Лаос" },
  { code: 'LB', dial: '961', en: "Lebanon", ru: "Ливан" },
  { code: 'MY', dial: '60', en: "Malaysia", ru: "Малайзия" },
  { code: 'MV', dial: '960', en: "Maldives", ru: "Мальдивы" },
  { code: 'MN', dial: '976', en: "Mongolia", ru: "Монголия" },
  { code: 'MM', dial: '95', en: "Myanmar", ru: "Мьянма" },
  { code: 'NP', dial: '977', en: "Nepal", ru: "Непал" },
  { code: 'KP', dial: '850', en: "North Korea", ru: "Северная Корея" },
  { code: 'OM', dial: '968', en: "Oman", ru: "Оман" },
  { code: 'PK', dial: '92', en: "Pakistan", ru: "Пакистан" },
  { code: 'PS', dial: '970', en: "Palestine", ru: "Палестина" },
  { code: 'PH', dial: '63', en: "Philippines", ru: "Филиппины" },
  { code: 'QA', dial: '974', en: "Qatar", ru: "Катар" },
  { code: 'SA', dial: '966', en: "Saudi Arabia", ru: "Саудовская Аравия" },
  { code: 'SG', dial: '65', en: "Singapore", ru: "Сингапур" },
  { code: 'KR', dial: '82', en: "South Korea", ru: "Южная Корея" },
  { code: 'LK', dial: '94', en: "Sri Lanka", ru: "Шри-Ланка" },
  { code: 'SY', dial: '963', en: "Syria", ru: "Сирия" },
  { code: 'TW', dial: '886', en: "Taiwan", ru: "Тайвань" },
  { code: 'TJ', dial: '992', en: "Tajikistan", ru: "Таджикистан" },
  { code: 'TH', dial: '66', en: "Thailand", ru: "Таиланд" },
  { code: 'TL', dial: '670', en: "Timor-Leste", ru: "Восточный Тимор" },
  { code: 'TR', dial: '90', en: "Turkey", ru: "Турция" },
  { code: 'TM', dial: '993', en: "Turkmenistan", ru: "Туркменистан" },
  { code: 'AE', dial: '971', en: "United Arab Emirates", ru: "ОАЭ" },
  { code: 'UZ', dial: '998', en: "Uzbekistan", ru: "Узбекистан" },
  { code: 'VN', dial: '84', en: "Vietnam", ru: "Вьетнам" },
  { code: 'YE', dial: '967', en: "Yemen", ru: "Йемен" },
  { code: 'HK', dial: '852', en: "Hong Kong", ru: "Гонконг" },
  { code: 'MO', dial: '853', en: "Macau", ru: "Макао" },
  { code: 'AL', dial: '355', en: "Albania", ru: "Албания" },
  { code: 'AD', dial: '376', en: "Andorra", ru: "Андорра" },
  { code: 'AT', dial: '43', en: "Austria", ru: "Австрия" },
  { code: 'BY', dial: '375', en: "Belarus", ru: "Беларусь" },
  { code: 'BE', dial: '32', en: "Belgium", ru: "Бельгия" },
  { code: 'BA', dial: '387', en: "Bosnia and Herzegovina", ru: "Босния и Герцеговина" },
  { code: 'BG', dial: '359', en: "Bulgaria", ru: "Болгария" },
  { code: 'HR', dial: '385', en: "Croatia", ru: "Хорватия" },
  { code: 'CZ', dial: '420', en: "Czech Republic", ru: "Чехия" },
  { code: 'DK', dial: '45', en: "Denmark", ru: "Дания" },
  { code: 'EE', dial: '372', en: "Estonia", ru: "Эстония" },
  { code: 'FI', dial: '358', en: "Finland", ru: "Финляндия" },
  { code: 'FR', dial: '33', en: "France", ru: "Франция" },
  { code: 'DE', dial: '49', en: "Germany", ru: "Германия" },
  { code: 'GR', dial: '30', en: "Greece", ru: "Греция" },
  { code: 'HU', dial: '36', en: "Hungary", ru: "Венгрия" },
  { code: 'IS', dial: '354', en: "Iceland", ru: "Исландия" },
  { code: 'IE', dial: '353', en: "Ireland", ru: "Ирландия" },
  { code: 'IT', dial: '39', en: "Italy", ru: "Италия" },
  { code: 'XK', dial: '383', en: "Kosovo", ru: "Косово" },
  { code: 'LV', dial: '371', en: "Latvia", ru: "Латвия" },
  { code: 'LI', dial: '423', en: "Liechtenstein", ru: "Лихтенштейн" },
  { code: 'LT', dial: '370', en: "Lithuania", ru: "Литва" },
  { code: 'LU', dial: '352', en: "Luxembourg", ru: "Люксембург" },
  { code: 'MT', dial: '356', en: "Malta", ru: "Мальта" },
  { code: 'MD', dial: '373', en: "Moldova", ru: "Молдова" },
  { code: 'MC', dial: '377', en: "Monaco", ru: "Монако" },
  { code: 'ME', dial: '382', en: "Montenegro", ru: "Черногория" },
  { code: 'NL', dial: '31', en: "Netherlands", ru: "Нидерланды" },
  { code: 'MK', dial: '389', en: "North Macedonia", ru: "Северная Македония" },
  { code: 'NO', dial: '47', en: "Norway", ru: "Норвегия" },
  { code: 'PL', dial: '48', en: "Poland", ru: "Польша" },
  { code: 'PT', dial: '351', en: "Portugal", ru: "Португалия" },
  { code: 'RO', dial: '40', en: "Romania", ru: "Румыния" },
  { code: 'RU', dial: '7', en: "Russia", ru: "Россия" },
  { code: 'SM', dial: '378', en: "San Marino", ru: "Сан-Марино" },
  { code: 'RS', dial: '381', en: "Serbia", ru: "Сербия" },
  { code: 'SK', dial: '421', en: "Slovakia", ru: "Словакия" },
  { code: 'SI', dial: '386', en: "Slovenia", ru: "Словения" },
  { code: 'ES', dial: '34', en: "Spain", ru: "Испания" },
  { code: 'SE', dial: '46', en: "Sweden", ru: "Швеция" },
  { code: 'CH', dial: '41', en: "Switzerland", ru: "Швейцария" },
  { code: 'UA', dial: '380', en: "Ukraine", ru: "Украина" },
  { code: 'GB', dial: '44', en: "United Kingdom", ru: "Великобритания" },
  { code: 'VA', dial: '379', en: "Vatican City", ru: "Ватикан" },
  { code: 'AU', dial: '61', en: "Australia", ru: "Австралия" },
  { code: 'FJ', dial: '679', en: "Fiji", ru: "Фиджи" },
  { code: 'KI', dial: '686', en: "Kiribati", ru: "Кирибати" },
  { code: 'MH', dial: '692', en: "Marshall Islands", ru: "Маршалловы Острова" },
  { code: 'FM', dial: '691', en: "Micronesia", ru: "Микронезия" },
  { code: 'NR', dial: '674', en: "Nauru", ru: "Науру" },
  { code: 'NZ', dial: '64', en: "New Zealand", ru: "Новая Зеландия" },
  { code: 'PW', dial: '680', en: "Palau", ru: "Палау" },
  { code: 'PG', dial: '675', en: "Papua New Guinea", ru: "Папуа - Новая Гвинея" },
  { code: 'WS', dial: '685', en: "Samoa", ru: "Самоа" },
  { code: 'SB', dial: '677', en: "Solomon Islands", ru: "Соломоновы Острова" },
  { code: 'TO', dial: '676', en: "Tonga", ru: "Тонга" },
  { code: 'TV', dial: '688', en: "Tuvalu", ru: "Тувалу" },
  { code: 'VU', dial: '678', en: "Vanuatu", ru: "Вануату" }
].sort((a, b) => a.en.localeCompare(b.en))

/** Flag emoji built from the ISO alpha-2 code (regional indicator symbols) - no image assets needed. */
export function flagEmoji(code: string): string {
  const cc = code.toUpperCase()
  if (cc.length !== 2) return '\uD83C\uDFF3\uFE0F'
  return String.fromCodePoint(...[...cc].map((c) => 127397 + c.charCodeAt(0)))
}
